#!/bin/bash
#SBATCH -J cyc_test_32_7n3c        # job name to display in squeue
#SBATCH -o test_32_7n3c.txt     # standard output file
#SBATCH -n 32                            # requested MPI tasks
#SBATCH -p standard-mem-s --mem=250G              # requested partition
#SBATCH -t 180                           # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe








