#!/bin/bash
#SBATCH -J cyc_test_64_7n3c.job         # job name to display in squeue
#SBATCH -o test_64_7n3c.txt     # standard output file
#SBATCH -N 2                            # requested nodes
#SBATCH --ntasks-per-node=32            # task load per node
#SBATCH -p standard-mem-s --mem=250G              # requested partition
#SBATCH -t 30                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe


