#!/bin/bash
#SBATCH -J test_64         # job name to display in squeue
#SBATCH -o test_64.txt     # standard output file
#SBATCH -N 1                            # requested nodes
#SBATCH -p standard-s               # requested partition
#SBATCH -t 2                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mem=256G
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe