#!/bin/bash
#SBATCH -J test_32_seq        # job name to display in squeue
#SBATCH -o test_32_dens20_seq.txt     # standard output file
#SBATCH -N 2                            # requested nodes
#SBATCH --ntasks-per-node=16            # task load per node#SBATCH -p standard-mem-m               # requested partition
#SBATCH -p standard-mem-s               # requested partition
#SBATCH -t 5                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe
