#!/bin/bash
#SBATCH -J test_8_seq        # job name to display in squeue
#SBATCH -o test_8_dens20_seq.txt     # standard output file
#SBATCH -n 8                            # requested MPI tasks
#SBATCH -p standard-mem-s               # requested partition
#SBATCH -t 5                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe
