#!/bin/bash
#SBATCH -J 256_test_7n3c         # job name to display in squeue
#SBATCH -o test_256_7n3c.txt     # standard output file
#SBATCH -N 8                            # requested nodes
#SBATCH --ntasks-per-node=32            # task load per node
#SBATCH -p medium-mem-1-s --mem=750G             # requested partition
#SBATCH -t 30                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe
