#!/bin/bash
#SBATCH -J test_64         # job name to display in squeue
#SBATCH -o test_64_dens20_cyc.txt     # standard output file
#SBATCH -N 2                            # requested nodes
#SBATCH --ntasks-per-node=32            # task load per node
#SBATCH -p medium-mem-1-s               # requested partition
#SBATCH -t 5                            # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

srun ./tabipb.exe
