#!/bin/bash
#SBATCH -J test_64_cyclic               # job name to display in squeue
#SBATCH -o test_scripts/test_64.txt     # standard output file
#SBATCH -n 64                           # requested MPI tasks
#SBATCH -p standard-s                   # requested partition
#SBATCH -t 180                          # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mem 256GB
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

mpirun ./tabipb.exe