#!/bin/bash
#SBATCH -J test_256_cyclic        # job name to display in squeue
#SBATCH -o test_scripts/test_256.txt     # standard output file
#SBATCH -N 4                            # requested nodes
#SBATCH --ntasks-per-node=64           # task load per node
#SBATCH -p standard-s               # requested partition
#SBATCH -t 180                           # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mem 256GB
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

mpirun ./tabipb.exe

