#!/bin/bash
#SBATCH -J test_2_dir       # job name to display in squeue
#SBATCH -o test_scripts/test_2_direct.txt     # standard output file
#SBATCH -n 2                            # requested MPI tasks
#SBATCH -p standard-s               # requested partition
#SBATCH -t 1000                           # maximum runtime in minutes
#SBATCH --exclusive                     # do not share nodes
#SBATCH --mem 256GB
#SBATCH --mail-user esliheet@smu.edu
#SBATCH --mail-type=all

mpirun ./tabipb.exe